name : C Unit CI
on:
 	push:
		braches:["main"]
 	pull_request:
		braches:["main"]
jobs:
	build:
		runs-on:Ubantu-latest
		steps:
		-name:ChangeCode
		 uses:action/code@v3
		-namne:install GCC
		 run:sudo apt update && sudo apt install -y build-essential
		-name :Build Project
		 run: make
		-name: Run executable
		 run:./main 
		